---

- name: Set up wheel users
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel ALL='
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add standard users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: wheel
    state: present
  with_items: "{{ users }}"
  no_log: true

- name: Add authorized keys for users
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized
  no_log: true

- name: Remove users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ remove_users }}"

- name: Add system-level authorized secrets for ssh users
  ansible.builtin.copy:
    content: '{{ item.key }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: "0600"
  with_items: "{{ system_users_private_keys }}"
  no_log: true
