---

- name: Add service-level authorized secrets for ssh users
  copy:
    content: '{{ item.key }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner }}'
    group: '{{ item.group }}'
    mode: 0600
  with_items: "{{ service_users_private_keys }}"
  no_log: true
  tags:
    - service-level
