---

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~/ansible-role-server-bootstrap
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install --dev
      - run:
          name: run tests
          command: |
            pipenv run molecule test
