---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-rockylinux8-ansible:latest
    command: /sbin/init
    privileged: true
    cgroupns: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
scenario:
  name: service-key
verifier:
  name: testinfra
