---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install sshd and dependencies
      ansible.builtin.dnf:
        name:
          - openssh
          - openssh-server
          - openssh-clients
          - openssl-libs
        state: present
        update_cache: yes
      become: true
    - name: start the sshd
      service:
        name: sshd
        state: started
  roles:
    - role: ansible-role-server-bootstrap
