---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:8
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: testinfra
