---
dependency:
  name: galaxy
  role-file: requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: "geerlingguy/docker-rockylinux9-ansible:latest"
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: testinfra
