name: Molecule Test

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  molecule:
    runs-on: [ systemd-runner ]
    strategy:
      matrix:
        python-version: [ "3.9.23" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pipenv"

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      

      - name: Install dependencies
        run: pipenv install --dev

      - name: Molecule test
        run: pipenv run molecule test


      

